---
####################################################
#          ModuleBuilder Configuration             #
####################################################
# Path to the Module Manifest to build (where path will be resolved from)
# SourcePath: ./Sampler/Sampler.psd1
# Output Directory where ModuleBuilder will build the Module, relative to module manifest
# OutputDirectory: ../output/Sampler
CopyPaths:
  #- HelperSubmodule # This will be built as submodule instead
  # - DSCResources
  - ../.build/tasks
  - scripts
  - en-US
  - Templates
Encoding: UTF8

# Suffix to add to Root module PSM1 after merge (here, the Set-Alias exporting IB tasks)
suffix: suffix.ps1
VersionedOutputDirectory: true
BuiltModuleSubdirectory: module

####################################################
#      ModuleBuilder Submodules Configuration      #
####################################################

NestedModule:

  # DscResource.Common:
  #   CopyOnly: true
  #   Path: ./output/RequiredModules/DscResource.Common # relative to $buildroot, default to '$sourcePath/Modules/$NestedModuleName'
  #   # Destination: './output/$ProjectName/$ModuleVersionFolder/Modules/$NestedModuleName' # or override with path relative to $buildroot
  #   AddToManifest: false
  #   # include: '*.*'
  #   Exclude: PSGetModuleInfo.xml
    #Filter:

####################################################
#              PESTER Configuration                #
####################################################

Pester:
  Configuration:
    Run:
      # Default is to use the tests folder in the project folder or source folder (if present)
      # can use it to prioritize: tests/QA, tests/Unit, tests/Integration
      Path:
        - tests/QA
        - tests/Unit
        #- tests/Unit/Public/Add-Sample.tests.ps1
        #- tests/Unit/Public/New-SampleModule.tests.ps1
        #- tests/Integration
    Output:
      Verbosity: Detailed
      StackTraceVerbosity: Full
      CIFormat: Auto
    CodeCoverage:
      CoveragePercentTarget: 70 # Set to 0 to bypass
      # Set to specific filename to override the default filename.
      #OutputPath: JaCoCo_coverage.xml
      OutputEncoding: ascii
      UseBreakpoints: false
    TestResult:
      OutputFormat: NUnitXML
      OutputEncoding: ascii
  # Will look at every *.ps1 & *.psm1 under ModulePath, excepts when $_.FullName -match (Join-Path $ProjectPath $ExcludeFromCodeCoverageItem)
  ExcludeFromCodeCoverage:
    - Templates
    - Modules/DscResource.Common
    - Assets
    # This is deprecated Pester 4 HQRM test, the HQRM test for Pester 5 has been
    # moved to module DscResource.Test.
    - tasks/DscResource.Test.build.ps1

####################################################
#           Code Coverage Configuration            #
####################################################

CodeCoverage:
  # Filename of the file that will be outputted by the task Merge_CodeCoverage_Files.
  CodeCoverageMergedOutputFile: JaCoCo_coverage.xml
  # File pattern used to search for files under the ./output/testResults folder
  # by task Merge_CodeCoverage_Files.
  CodeCoverageFilePattern: Codecov*.xml

####################################################
#             HQRM Test Configuration              #
####################################################

DscTest:
  Pester:
    Configuration:
      Filter:
        ExcludeTag:
          - "Common Tests - New Error-Level Script Analyzer Rules"
          - "Common Tests - Validate Localization"
          - "Common Tests - Validate Example Files To Be Published"
          - "Common Tests - Validate Example Files"
      Output:
        Verbosity: Detailed
        CIFormat: Auto
      TestResult:
        OutputFormat: NUnitXML
        OutputEncoding: ascii
        OutputPath: ./output/testResults/NUnitXml_HQRM_Tests.xml
  Script:
    ExcludeSourceFile:
      - output
      - Modules/DscResource.Common
    ExcludeModuleFile:
      - Templates
      - Modules/DscResource.Common
    MainGitBranch: main

####################################################
#       Sampler Pipeline Configuration             #
####################################################
# Defining 'Workflows' (suite of InvokeBuild tasks) to be run using their alias
BuildWorkflow:

  '.': # "." is the default Invoke-Build workflow. It is called when no -Tasks is specified to the build.ps1
    - build
    - test

  build:
    - Clean
    - Build_Module_ModuleBuilder
    - Build_NestedModules_ModuleBuilder
    - Create_changelog_release_output

  docs:
    # The meta task Generate_Wiki_Content is not used so that Linux and macOS is supported
    # - Generate_Conceptual_Help # Used for DSC resources
    - Create_Wiki_Output_Folder
    # - Generate_Markdown_For_DSC_Resources # Used for DSC resources
    - Generate_Markdown_For_Public_Commands
    - Generate_External_Help_File_For_Public_Commands
    - Clean_Markdown_Of_Public_Commands
    - Copy_Source_Wiki_Folder
    - Generate_Wiki_Sidebar
    - Clean_Markdown_Metadata
    - Package_Wiki_Content

  pack:
    - build
    - docs
    - package_module_nupkg

  hqrmtest:
    - Invoke_HQRM_Tests_Stop_On_Fail

  # defining test task to be run when invoking `./build.ps1 -Tasks test`
  test:
    - Pester_Tests_Stop_On_Fail
    - Convert_Pester_Coverage
    - Pester_if_Code_Coverage_Under_Threshold
    - hqrmtest

  merge:
    - Merge_CodeCoverage_Files

  publish:
    - Publish_release_to_GitHub # Runs first, if token is expired it will fail early
    #- publish_nupkg_to_gallery  # Deploy using Nuget
    - publish_module_to_gallery # Deploy using cmdlet Publish-Module
    - Publish_GitHub_Wiki_Content

# Import ModuleBuilder tasks from a specific PowerShell module using the build
# task's alias. Wildcard * can be used to specify all tasks that has a similar
# prefix and or suffix. The module contain the task must be added as a required
# module in the file RequiredModules.psd1.
ModuleBuildTasks:
  Sampler.GitHubTasks:
    - '*.ib.tasks'
  DscResource.Test:
    - 'Task.*'
  DscResource.DocGenerator:
    - 'Task.*'

# Invoke-Build Header to be used to 'decorate' the terminal output of the tasks.
TaskHeader: |
  param($Path)
  ""
  "=" * 79
  Write-Build Cyan "`t`t`t$($Task.Name.replace("_"," ").ToUpper())"
  Write-Build DarkGray  "$(Get-BuildSynopsis $Task)"
  "-" * 79
  Write-Build DarkGray "  $Path"
  Write-Build DarkGray "  $($Task.InvocationInfo.ScriptName):$($Task.InvocationInfo.ScriptLineNumber)"
  ""

GitHubConfig:
  GitHubFilesToAdd:
    - 'CHANGELOG.md'
  ReleaseAssets:
    - output/WikiContent.zip
  GitHubConfigUserName: gaelcolas
  GitHubConfigUserEmail: gaelcolas@synedgy.com
  UpdateChangelogOnPrerelease: false

#SetPSModulePath:
  #PSModulePath: C:\Users\<UserName>\OneDrive\Documents\WindowsPowerShell\Modules;C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\WindowsPowerShell\v1.0\Modules;
  #RemovePersonal: true
  #RemoveProgramFiles: true
  #RemoveWindows: false
  #SetSystemDefault: false

####################################################
#      DscResource.DocGenerator Configuration      #
####################################################
DscResource.DocGenerator:
  # Generate_Conceptual_Help:
  #   MarkdownCodeRegularExpression:
  #     - '\`(.+?)\`' # Match inline code-block
  #     - '\\(\\)' # Match escaped backslash
  #     - '\[[^\[]+\]\((.+?)\)' # Match markdown URL
  #     - '_(.+?)_' # Match Italic (underscore)
  #     - '\*\*(.+?)\*\*' # Match bold
  #     - '\*(.+?)\*' # Match Italic (asterisk)
  Publish_GitHub_Wiki_Content:
    Debug: false
  Generate_Wiki_Content:
    # MofResourceMetadata:
    #   Type: MofResource
    #   Category: Resources
    # ClassResourceMetadata:
    #   Type: ClassResource
    #   Category: Resources
    # CompositeResourceMetadata:
    #   Type: CompositeResource
    #   Category: Resources
  Generate_Wiki_Sidebar:
     Debug: false
     AlwaysOverwrite: true
