trigger:
- master

pool:
  vmImage: 'ubuntu 16.04'
#variables:

steps:
- task: GitVersion@5
  name: gitversion
  inputs:
    runtime: 'core'
    configFilePath: 'GitVersion.yml'

- task: PowerShell@2
  name: Build
  inputs:
    filePath: './build.ps1'
    arguments: '-ResolveDependency -tasks build'
    pwsh: true
  env:
    ModuleVersion: $(GitVersion.NuGetVersionV2)

- task: PowerShell@2
  name: Test
  inputs:
    filePath: './build.ps1'
    arguments: '-tasks test'
    pwsh: true
  env:
    ModuleVersion: $(GitVersion.NuGetVersionV2)

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'NUnit'
    testResultsFiles: 'output/testResults/NUnit*.xml'


# Publish code coverage results
- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'JaCoCo'
    summaryFileLocation: 'output/testResults/CodeCov*.xml'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: 'output/'
    artifact: 'BuiltModule'
    publishLocation: 'pipeline'
    parallel: true
