                # '.github'
                # '.github/ISSUE_TEMPLATE'
                # '.github/ISSUE_TEMPLATE/General.md'
                # '.github/ISSUE_TEMPLATE/Problem_with_resource.md'
                # '.github/ISSUE_TEMPLATE/Resource_proposal.md'
                # '.github/PULL_REQUEST_TEMPLATE.md'
