name: Problem with the module
description: If you have a problem using this module, want to report a bug, or suggest an enhancement to this module.
labels: []
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for contributing! Please be descriptive in your title, and fill in the sections below.
        **Write N/A in sections that do not apply, or if the information is not available.**
  - type: textarea
    id: description
    attributes:
      label: Problem description
      description: What did you try, what happened, and what did you expect to happen? Include the steps to reproduce.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Verbose logs
      description: |
        Verbose logs showing the problem. **Sensitive information should be obfuscated.** _Will be automatically formatted as plain text._
      placeholder: |
        Paste verbose logs here
      render: text
    validations:
      required: true
  - type: textarea
    id: suggestedSolution
    attributes:
      label: Suggested solution
      description: Do you have any suggestions how to solve the issue? (Optional)
    validations:
      required: false
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        The OS, PowerShell version/build, and Sampler module version in use. _Will be automatically formatted as plain text._

        Helpful commands:
        - OS: `Get-ComputerInfo` (Windows), `cat /etc/*-release && cat /proc/version` (Linux), `sw_vers` (macOS)
        - PowerShell: `$PSVersionTable`
        - Module version: `Get-Module -Name 'Sampler' -ListAvailable | ft Name,Version,Path`
      placeholder: |
        Add environment information here
      render: text
    validations:
      required: true
